% function plotDHRasterCustom(i_cell)

i_cell = 71;
n_rasters = 4;

figure()
fullScreen()

plotDHRaster(i_cell, 'DHSingle20', 'single', ...
    'Is_Subfigure', true, ...
    'Columns_Indices', 1, ...
    'Dead_Times', true, ...
    'N_Columns', n_rasters)

plotDHRaster(i_cell, 'DHSingle20', 'single', ...
    'Is_Subfigure', true, ...
    'Columns_Indices', 2, ...
    'Dead_Times', true, ...
    'N_Columns', n_rasters, ...
    'PSTH_Mode', true)

plotDHRaster(i_cell, 'DHMulti20', 'single', ...
    'Is_Subfigure', true, ...
    'Columns_Indices', 3, ...
    'Dead_Times', true, ...
    'N_Columns', n_rasters)

plotDHRaster(i_cell, 'DHMulti20', 'test', ...
    'Is_Subfigure', true, ...
    'Columns_Indices', 4, ...
    'Dead_Times', true, ...
    'N_Columns', n_rasters)