
% Parameters
exp_id = '20180705_discs';
discs_mat_file = [stimPath '/Discs/180704_PairedPulseBg_230_Manip.mat'];
discs_vec_file = [stimPath '/Discs/180704_PairedPulseBg_230_Manip.vec'];
mea_rate = 20000; % Hz
Checkerboard_PxlsPerSquare = 20;

% Plots Params
tBin = 0.05; % s
spacing = 2; % s
i_disc_plot = 1;

% Paths
exp_id = char(exp_id);
vars_path = [dataPath(), '/' exp_id '/processed'];
discs_path = [vars_path() '/Discs'];
stims_order_file = [vars_path '/stims_order.txt'];

% Stim Triggers
load([vars_path '/EvtTimes.mat'], 'evtTimes')
disp("EvtTimes Loaded")

% Spike Times
load([vars_path '/SpikeTimes.mat'], 'SpikeTimes')
disp("Spike Times Loaded")

% Retrieve the order of Stimulations
stims_order = importdata(stims_order_file);
discs_index = contains(stims_order, 'DISCS');

% Discs Repetitions
discs_triggers = evtTimes{discs_index}.evtTimes_begin;
discs_stim_info = getDiscsStimInfo(discs_mat_file, discs_vec_file);
discs_reps = getDiscsRepetitions(discs_triggers, discs_stim_info);

for i_disc = 1:numel(discs_reps)
    center_x_dmd = discs_reps(i_disc).center_x / Checkerboard_PxlsPerSquare;
    center_y_dmd = discs_reps(i_disc).center_y / Checkerboard_PxlsPerSquare;
    h1 = getHomography('dmd', 'img');
    h2 = getHomography('img1', 'mea', exp_id);
    h = h2*h1;
    [center_x_mea, center_y_mea] = transformPoints(h, center_y_dmd, center_x_dmd);
    
    discs_reps(i_disc).center_x_dmd = center_x_dmd;
    discs_reps(i_disc).center_y_dmd = center_y_dmd;
    discs_reps(i_disc).center_x_mea = center_y_mea;
    discs_reps(i_disc).center_y_mea = center_x_mea;
    
end

save([tmpPath() '/' 'Discs_RepetitionTimes.mat'], 'discs_reps')
movefile([tmpPath() '/' 'Discs_RepetitionTimes.mat'], discs_path)

save(getDatasetMat, 'discs_reps', '-append')
% Test Checkerboard
% figure
% n_steps = mean(discs_reps(i_disc_plot).rep_end - discs_reps(i_disc_plot).rep_begin);
% 
% subplot(1, 5, 1);
% plotCellsRaster(SpikeTimes(1:20), ...
%                 discs_reps(i_disc_plot).rep_begin, ...
%                 n_steps, mea_rate, ...
%                 'Column_Size', 20, ...
%                 'Response_Onset_Seconds', -spacing, ...
%                 'Response_Offset_Seconds', spacing, ...
%                 'Bins_Onset_Seconds', 0.5, ...
%                 'Bins_Offset_Seconds', 2);
% 
% subplot(1, 5, 2);
% plotCellsRaster(SpikeTimes(21:40), ...
%                 discs_reps(i_disc_plot).rep_begin, ...
%                 n_steps, mea_rate, ...
%                 'Column_Size', 20, ...
%                 'Response_Onset_Seconds', -spacing, ...
%                 'Response_Offset_Seconds', spacing, ...
%                 'Bins_Onset_Seconds', 0.5, ...
%                 'Bins_Offset_Seconds', 2);
%             
% subplot(1, 5, 3);
% plotCellsRaster(SpikeTimes(41:60), ...
%                 discs_reps(i_disc_plot).rep_begin, ...
%                 n_steps, mea_rate, ...
%                 'Column_Size', 20, ...
%                 'Response_Onset_Seconds', -spacing, ...
%                 'Response_Offset_Seconds', spacing, ...
%                 'Bins_Onset_Seconds', 0.5, ...
%                 'Bins_Offset_Seconds', 2);
%             
% subplot(1, 5, 4);
% plotCellsRaster(SpikeTimes(61:80), ...
%                 discs_reps(i_disc_plot).rep_begin, ...
%                 n_steps, mea_rate, ...
%                 'Column_Size', 20, ...
%                 'Response_Onset_Seconds', -spacing, ...
%                 'Response_Offset_Seconds', spacing, ...
%                 'Bins_Onset_Seconds', 0.5, ...
%                 'Bins_Offset_Seconds', 2);
%             
% subplot(1, 5, 5);
% plotCellsRaster(SpikeTimes(81:100), ...
%                 discs_reps(i_disc_plot).rep_begin, ...
%                 n_steps, mea_rate, ...
%                 'Column_Size', 20, ...
%                 'Response_Onset_Seconds', -spacing, ...
%                 'Response_Offset_Seconds', spacing, ...
%                 'Bins_Onset_Seconds', 0.5, ...
%                 'Bins_Offset_Seconds', 2);
%             
% suptitle("CheckerBoard Raster")

